---
title: "Report for ancestral area estimation using the FIG model"
author: Friederike Wölke
date: 2026-06-24
format: html
embed-resources: true
standalone: true
toc: true
---

# FIG model

> The FIG model extends the GeoSSE model by allowing regional features to shape biogeographic rates (Landis et al. 2022; Swiston and Landis 2023). The purpose of FIG is to allow biologists to test new hypotheses that involve the timing and location of phylogenetic, biogeographic, and paleogeographic events. *Source*: https://revbayes.github.io/tutorials/fig_intro/

## TimeFIG

> Dating with TimeFIG jointly estimates phylogenetic divergence times, molecular substitution rates, biogeographic rates, and ancestral species ranges. The tutorial provides a conceptual background on challenges related to dating molecular phylogenies, alternative techniques for dating, and a framework to assess the sensitivity of divergence time estimates to methodological assumptions. *Source*: https://revbayes.github.io/tutorials/timefig_dating/#molecular-phylogenetics

## Requirements:

<https://revbayes.github.io/tutorials/docker/>

-   **Docker (+ DockerHub account)** to install **PhyloDocker** image from <https://hub.docker.com/r/sswiston/phylo_docker>
    -   open Docker Desktop

    -   download image from [url](https://hub.docker.com/r/sswiston/phylo_docker): open **Git Bash** and run:

        ```         
        docker pull sswiston/phylo_docker:rev_update
        ```

    -   open the image: *(from powershell works)*

        ```         
        docker run --name RevBayes_docker2 `
          -v "${PWD}:/FIG_model" `
          -it sswiston/phylo_docker:rev_update /bin/sh
        ```

    -   start the container: `start RevBayes_docker 2`

    -   Open the container: `exec -it RevBayes_docker2 /bin/sh`

    -   `cd` to `FIG_model`

    -   start RevBayes with: `rb`

    -   `loadPlugin("TensorPhylo")`

    -   run RevBayes scripts like this: `rb scripts/fig-model/1_molecular_phylogenetics/01_divtime_uncalibrated.Rev`



## Prepare the PALEOMAP to extract biogeographic features for Africa and Madagascar through time

```{bash}
#| eval: false
conda create -n pygplates
conda activate pygplates

python3 -m venv pygplates_venv
source pygplates_venv/bin/activate
python -m pip install pygplates
python -m pip install gplately
```


```{python}
from pathlib import Path
import pygplates

gpml_files = list(Path("gplates_files").glob("*.gpml"))
rot_files = list(Path("gplates_files").glob("*.rot"))

print("GPML files:")
for f in gpml_files:
    print(" ", f)

print("Rotation files:")
for f in rot_files:
    print(" ", f)

```

### A) Biogeographic dating with node dating (fixed tree)

### B) Biogeographic dating with molecular clock (tree as random variable)