---
title: "Report for GeoSSE model"
author: Friederike Wölke
date: 2026-06-25
format: html
embed-resources: true
standalone: true
toc: true
---

Source: https://revbayes.github.io/tutorials/geosse/

# Model overview

*Core processes*: - within-region speciation (cladogenetic - at the nodes; within regions) - local extinction (anagenetic - along branches; within regions) - between-region speciation (cladogenetic - at the nodes; between regions) - dispersal (anagenetic - along the branches; between regions)

> *Here is a summary of the four event types:*

> -   Extinction causes a species to lose one region from its range. Only when a species loses the final region from its range, does the entire species go entirely extinct as a lineage. A widespread lineage can only go extinct by losing each of its regions individually until one remains, then losing that last region. For example, a species with range AB might go extinct in region A, leaving it with range B. If it experiences no dispersal events (below) and suffers extinction in its last region B, the species is completely extinct.
> -   Dispersal causes a species to expand its range into a new region. The rate of range expansion is the sum of pairwise dispersal rates from each starting region into the new region. For example, a species with range A that disperses into region B afterwards has range AB.
> -   Within-region speciation: One daughter lineage inherits the entire ancestral range (which may be one or more regions), while the other daughter inherits a single region from the ancestral range. For example, the ancestral species has range AB and its two daughter species have ranges AB and A.
> -   Between-region speciation: The range of a widespread ancestral species in two or more regions is subdivided and inherited by two new daughter lineages. Between-region speciation rates are always symmetric (separation between A and B is the same as separation between B and A). For example, the widespread ancestor with range AB splits and give rise to daughters with ranges A and B.

> *Limits:* The standard GeoSSE model does not allow for other kinds of evolutionary events. For example, an ancestor with a widespread range (of two or more regions) cannot produce daughters that both possess the entire ancestral range (a widespread sympatry scenario). In addition, GeoSSE only allows for a single event to occur within an instant of time.

# Workflow

*Requirements for the model*: - time-calibrated phylogeny - biogeographic data matrix describing the ranges for each species

*NOTE*: Geosse requires the plugin TensorPhylo which comes wrapped in a docker image that can be installed as follows:

-   **Docker (+ DockerHub account)** to install **PhyloDocker** image from <https://hub.docker.com/r/sswiston/phylo_docker>
-   open Docker Desktop
-   download image from [url](https://hub.docker.com/r/sswiston/phylo_docker): open **Git Bash** and run:\
    `docker pull sswiston/phylo_docker:rev_update`
-   open the image: *(from powershell works)*\
    `` docker run --name RevBayes_docker2 ` -v "${PWD}:/FIG_model" ` -it sswiston/phylo_docker:rev_update /bin/sh ``
-   start the container: `start RevBayes_docker2`
-   Open the container: `exec -it RevBayes_docker2 /bin/sh`
-   `cd` to `FIG_model`
-   start RevBayes with: `rb`
-   `loadPlugin("TensorPhylo")`
-   run RevBayes scripts like this: `rb scripts/fig-model/1_molecular_phylogenetics/01_divtime_uncalibrated.Rev`

## Setup the data

```{bash}
#| eval: false

# Set Variables with filepaths (fp)
dat_fp = "./data/input/"
out_fp = "./data/output/GeoSSE/"
bg_fn  = dat_fp + "Uapaca_range.nex"
phy_fn = "./data/output/divtime_uncalibrated/divtime_uncalibrated.mcc.tre"
lbl_fn = outfp + "range_state_labels.txt"
```

```{bash}
#| eval: false

# Read the tree
phy <- readTrees(phy_fn)[1]

# save some information about the phylogeny
tree_height <- phy.rootAge()
taxa = phy.taxa()
num_taxa = taxa.size()
```

```{bash}
#| eval: false

# Biogeographic (Range) data
bg_01 = readDiscreteCharacterData(bg_fn)

# save some information about the ranges
num_regions = bg_01.nchar()
num_ranges = abs(2^num_regions - 1)
num_pairs = num_regions^2 - num_regions

# Convert the ranges into GeoSSE format
bg_dat = formatDiscreteCharacterData(bg_01, format="GeoSSE", numStates=num_ranges)
```

## Setup the model

> *For each process, each distinct event is assigned its own rate that depends on the involved regions or region pairs.* 

[**Processes:**]{.underline}

-   [e = Extinction]{.smallcaps}
-   [d = Dispersal]{.smallcaps}
-   [w = Within-region speciation]{.smallcaps}
-   [b = Between-region speciation]{.smallcaps}

[**Parameters:**]{.underline}

-   r = rate parameter
-   m = relative rate parameter for each event class (x)
-   rho = base rate parameter for each event class (x)

```{bash}
#| eval: false

# within-region rates
r_w
r_e

# between-region rates
r_b
r_d

# relative rate parameter
m_x

# base rate parameter
rho_x

# absolute rates
r_x
```

### i. within-region speciation (w)

```{bash}
#| eval: false

# stochastic rho_x will be drawn from exponential distribution
rho_w ~ dnExp(1)

# stochastic relative parameters will be drawn from Dirichlet
m_w_simplex ~ dnDirichlet(rep(1,num_regions))

# determinisitc relative rates for each region
m_w := m_w_simplex * num_regions

# determinisitc absolute rates for each region
r_w := rho_w * m_w
```

### ii. local extinction (e)
follow the same setup as within-region speciation

```{bash}
#| eval: false

# stochastic rho_x will be drawn from exponential distribution
rho_e ~ dnExp(1)

# stochastic relative parameters will be drawn from Dirichlet
m_e_simplex ~ dnDirichlet(rep(1,num_regions))

# determinisitc relative rates for each region
m_e := m_e_simplex * num_regions

# determinisitc absolute rates for each region
r_e := rho_e * m_e
```

### iii. global extinction (mu)
All multi-region rates will be assinged = 0 because a species needs to lose all regions for global extinction. 
```{bash}
#| eval: false


for (i in 1:num_ranges) {
    mu[i] <- 0.0
    if (i <= num_regions) {
        mu[i] := r_e[i]
    }
}
```


### iv. between-region speciation (b)
Assign rates to each region-pair. The rates will be symmetric, meaning there are only num_pairs/2 unique values. Thus we have to assin the same value to *m_b[i][j]* as *m_b[j][i]*. We can do this by creating an initial simplex from a Dirichlet distribution, and assigning successive values from this simplex as we traverse the m_b matrix.

> Since we only have two regions, the result *m_b_simplex* will contain only a single relative-rate factor of *1*. That means the value of *r_b* for between-region speciation is driven entirely by *rho_b*


```{bash}
#| eval: false

# exponential base rate
rho_b ~ dnExp(1)

# stochastic relative rate
m_b_simplex ~ dnDirichlet(rep(1,num_pairs/2))

# counter for loop
m_b_idx = 1
for (i in 1:num_regions) {
    m_b[i][i] <- 0.0
    for (j in 1:num_regions) {
        if (i < j) {
            m_b[i][j] := abs(m_b_simplex[m_b_idx] * num_pairs)
            m_b[j][i] := abs(m_b_simplex[m_b_idx] * num_pairs)
            m_b_idx += 1
        }
        r_b[i][j] := rho_b * m_b[i][j]
    }
}
```

### v. dispersal (d)
Finally, for dispersal rates, we want to assign rates to each region pair. These rates are allowed to be asymmetric, so we need num_pairs unique values. In this case 1.

```{bash}
# base rate
rho_d ~ dnExp(1)

# relative dispersal rate
m_d_simplex ~ dnDirichlet(rep(1,num_pairs))

# counter for loop
m_d_idx = 1
for (i in 1:num_regions) {
    m_d[i][i] <- 0.0
    for (j in 1:num_regions) {
        if (i != j) {
            m_d[i][j] := abs(m_d_simplex[m_d_idx++] * num_pairs)
        }
        r_d[i][j] := rho_d * m_d[i][j]
    }
}

```


## Construct the rate matrices

### i. Anagenetic rate matrix

```{bash}
Q_bg := fnBiogeographyRateMatrix(
    dispersalRates=r_d,
    extirpationRates=r_e,
    maxRangeSize=num_regions
)
```

### ii. Cladogenetic rate matrix
Describing the absolut rates of different cladogenetic events (speciation: w, b)

```{bash}
clado_map := fnBiogeographyCladoEventsBD(
    speciation_rates=[rho_w,rho_b],
    within_region_features=m_w,
    between_region_features=m_b,
    max_range_size=num_regions,
    max_subrange_split_size=num_regions
)

# Speciation rates per state:
lambda := clado_map.getSpeciationRateSumPerState()

# Cladogenetic probability matrix: 
omega := clado_map.getCladogeneticProbabilityMatrix()
```

### iii. MRCA state
Set up a probability distribution to assign to the range of the MRCA of all species prior to the first speciation event.
```{bash}
# we will assume both ancestral states are equally likely
pi_base <- rep(1,num_ranges)
pi <- simplex(pi_base)
```

## Bringing all rates together:

```{bash}
# Stochastic variable that describes how processes interact to generate a tree topology, divergence times and terminal taxon ranges.
# dnGLHBDSP distribution (Generalized Lineage Heterogeneous Birth Death Sampling Process)

timetree ~ dnGLHBDSP(
    rootAge     = tree_height,
    lambda      = lambda,
    mu          = mu,
    eta         = Q_bg,
    omega       = omega,
    pi          = pi,
    rho         = 1.0,
    condition   = "time",   # condition the likelihood on time 
    taxa        = taxa,
    nStates     = num_ranges,
    nProc       = 4         # 4 processors
)

# infer model parameters from our observed data: 
timetree.clamp(phy)
timetree.clampCharData(bg_dat)
```


## MCMC
### i. setup MCMC parameters
```{bash}
n_gen = 1000
n_burn = 100
printgen = 10
```

### ii. moves
```{bash}
mvi = 1
mv[mvi++] = mvScale(rho_w, weight=1)
mv[mvi++] = mvScale(rho_e, weight=1)
mv[mvi++] = mvScale(rho_b, weight=1)
mv[mvi++] = mvScale(rho_d, weight=1)
mv[mvi++] = mvSimplex(m_e_simplex, weight=m_e.size())
mv[mvi++] = mvSimplex(m_w_simplex, weight=m_w.size())
mv[mvi++] = mvSimplex(m_b_simplex, weight=m_b_simplex.size())
mv[mvi++] = mvSimplex(m_d_simplex, weight=m_d_simplex.size())
```

### iii. monitors

```{bash}
mni = 1
mn[mni++] = mnScreen(printgen=printgen)
mn[mni++] = mnModel(printgen=printgen, filename=out_fp+"model.log")
mn[mni++] = mnJointConditionalAncestralState(glhbdsp=timetree, tree=timetree, printgen=printgen, filename=out_fp+"states.log", withTips=true, withStartStates=true, type="NaturalNumbers")
mn[mni++] = mnStochasticCharacterMap(glhbdsp=timetree, printgen=printgen, filename=out_fp+"stoch.log")
```


### iv. save range labels to file

```{bash}
write("index,range\n", file=lbl_fn)
state_labels = Q_bg.getStateDescriptions()
for (i in 1:state_labels.size()) {
    write( (i-1), ",", state_labels[i], "\n", file=lbl_fn, append=true, separator="")
}
```

### v. set up model 

does not matter which parameter we chose to model, the process will find all other parameters as well. 
```{bash}
mdl = model(m_w)
ch = mcmc(mv, mn, mdl)
ch.burnin(n_burn, tuningInterval=50)
ch.run(n_gen)
```

## Summarize ancestral states


```{bash}
f_burn = 0.2
x_stoch = readAncestralStateTrace(file=out_fp+"stoch.log")
x_states = readAncestralStateTrace(file=out_fp+"states.log")
summarizeCharacterMaps(x_stoch,timetree,file=out_fp+"events.tsv",burnin=f_burn)
state_tree = ancestralStateTree(tree=timetree,
                   ancestral_state_trace_vector=x_states,
                   include_start_states=true,
                   file=out_fp+"ase.tre",
                   summary_statistic="MAP",
                   reconstruction="marginal",
                   burnin=f_burn,
                   nStates=3,
                   site=1)
writeNexus(state_tree,filename=out_fp+"ase.tre")
```